        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:22 2011
        MODULE AQUIRE_HGRID__genmod
          INTERFACE 
            SUBROUTINE AQUIRE_HGRID(FULL_AQUIRE)
              LOGICAL(KIND=4), INTENT(IN) :: FULL_AQUIRE
            END SUBROUTINE AQUIRE_HGRID
          END INTERFACE 
        END MODULE AQUIRE_HGRID__genmod
