        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:22 2011
        MODULE AQUIRE_VGRID__genmod
          INTERFACE 
            SUBROUTINE AQUIRE_VGRID
            END SUBROUTINE AQUIRE_VGRID
          END INTERFACE 
        END MODULE AQUIRE_VGRID__genmod
