        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE CHAR_NUM__genmod
          INTERFACE 
            FUNCTION CHAR_NUM(NUM) RESULT(CHAR_NUM_0)
              INTEGER(KIND=4), INTENT(IN) :: NUM
              CHARACTER(LEN=3) :: CHAR_NUM_0
            END FUNCTION CHAR_NUM
          END INTERFACE 
        END MODULE CHAR_NUM__genmod
