        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE CHECK_ALLOCATION__genmod
          INTERFACE 
            SUBROUTINE CHECK_ALLOCATION(VARIABLE,LOCATION,STATUS)
              CHARACTER(*), INTENT(IN) :: VARIABLE
              CHARACTER(*), INTENT(IN) :: LOCATION
              INTEGER(KIND=4), INTENT(IN) :: STATUS
            END SUBROUTINE CHECK_ALLOCATION
          END INTERFACE 
        END MODULE CHECK_ALLOCATION__genmod
