        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:09 2011
        MODULE COMBINE_SFLUX_DATA__genmod
          INTERFACE 
            SUBROUTINE COMBINE_SFLUX_DATA(TIME_NOW,INFO_1,INFO_2,READ_1,&
     &READ_2,DATA_NAME,DATA_OUT,NUM_NODES_OUT)
              USE NETCDF_IO
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES_OUT
              REAL(KIND=8), INTENT(IN) :: TIME_NOW
              TYPE (DATASET_INFO), INTENT(IN) :: INFO_1
              TYPE (DATASET_INFO), INTENT(IN) :: INFO_2
              LOGICAL(KIND=4), INTENT(IN) :: READ_1
              LOGICAL(KIND=4), INTENT(IN) :: READ_2
              CHARACTER(*), INTENT(IN) :: DATA_NAME
              REAL(KIND=8), INTENT(OUT) :: DATA_OUT(NUM_NODES_OUT)
            END SUBROUTINE COMBINE_SFLUX_DATA
          END INTERFACE 
        END MODULE COMBINE_SFLUX_DATA__genmod
