        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:11 2011
        MODULE DO_TRANSPORT_TVD__genmod
          INTERFACE 
            SUBROUTINE DO_TRANSPORT_TVD(IT,IMOD,UP_TVD,TVD_MID,FLIMITER,&
     &NTR,DIFNUM_MAX_L)
              USE ELFE_GLBL
              INTEGER(KIND=4), INTENT(IN) :: NTR
              INTEGER(KIND=4), INTENT(IN) :: IT
              INTEGER(KIND=4), INTENT(IN) :: IMOD
              LOGICAL(KIND=4), INTENT(IN) :: UP_TVD
              CHARACTER(LEN=2), INTENT(IN) :: TVD_MID
              CHARACTER(LEN=2), INTENT(IN) :: FLIMITER
              REAL(KIND=8), INTENT(OUT) :: DIFNUM_MAX_L
            END SUBROUTINE DO_TRANSPORT_TVD
          END INTERFACE 
        END MODULE DO_TRANSPORT_TVD__genmod
