        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_WEIGHT__genmod
          INTERFACE 
            SUBROUTINE GET_WEIGHT(X_IN,Y_IN,X_OUT,Y_OUT,ELEM_NODES,     &
     &NODE_I,NODE_J,NX,NY,NUM_ELEMS,NUM_NODES,NUM_NODES_OUT,            &
     &IN_ELEM_FOR_OUT_NODE,WEIGHT)
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES_OUT
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES
              INTEGER(KIND=4), INTENT(IN) :: NUM_ELEMS
              INTEGER(KIND=4), INTENT(IN) :: NY
              INTEGER(KIND=4), INTENT(IN) :: NX
              REAL(KIND=8), INTENT(IN) :: X_IN(NX,NY)
              REAL(KIND=8), INTENT(IN) :: Y_IN(NX,NY)
              REAL(KIND=8), INTENT(IN) :: X_OUT(NUM_NODES_OUT)
              REAL(KIND=8), INTENT(IN) :: Y_OUT(NUM_NODES_OUT)
              INTEGER(KIND=4), INTENT(IN) :: ELEM_NODES(NUM_ELEMS,3)
              INTEGER(KIND=4), INTENT(IN) :: NODE_I(NUM_NODES)
              INTEGER(KIND=4), INTENT(IN) :: NODE_J(NUM_NODES)
              INTEGER(KIND=4), INTENT(OUT) :: IN_ELEM_FOR_OUT_NODE(     &
     &NUM_NODES_OUT)
              REAL(KIND=8), INTENT(OUT) :: WEIGHT(NUM_NODES_OUT,3)
            END SUBROUTINE GET_WEIGHT
          END INTERFACE 
        END MODULE GET_WEIGHT__genmod
