        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:19 2011
        MODULE GET_PARAM__genmod
          INTERFACE 
            SUBROUTINE GET_PARAM(VARNAME,VARTYPE,IVARVALUE,VARVALUE1,   &
     &VARVALUE2)
              CHARACTER(*), INTENT(IN) :: VARNAME
              INTEGER(KIND=4), INTENT(IN) :: VARTYPE
              INTEGER(KIND=4), INTENT(OUT) :: IVARVALUE
              REAL(KIND=8), INTENT(OUT) :: VARVALUE1
              CHARACTER(LEN=2), INTENT(OUT) :: VARVALUE2
            END SUBROUTINE GET_PARAM
          END INTERFACE 
        END MODULE GET_PARAM__genmod
