        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_FILE_TIMES__genmod
          INTERFACE 
            SUBROUTINE GET_FILE_TIMES(FILE_NAME,FILE_TIMES,             &
     &FILE_JULIAN_DATE,MAX_FILE_TIMES,NUM_FILE_TIMES)
              INTEGER(KIND=4), INTENT(IN) :: MAX_FILE_TIMES
              CHARACTER(LEN=50), INTENT(IN) :: FILE_NAME
              REAL(KIND=8), INTENT(OUT) :: FILE_TIMES(MAX_FILE_TIMES)
              INTEGER(KIND=4), INTENT(OUT) :: FILE_JULIAN_DATE
              INTEGER(KIND=4), INTENT(OUT) :: NUM_FILE_TIMES
            END SUBROUTINE GET_FILE_TIMES
          END INTERFACE 
        END MODULE GET_FILE_TIMES__genmod
