        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_FILE_NAME__genmod
          INTERFACE 
            FUNCTION GET_FILE_NAME(DATASET_NAME,NUM) RESULT(            &
     &GET_FILE_NAME_0)
              CHARACTER(LEN=50), INTENT(IN) :: DATASET_NAME
              INTEGER(KIND=4), INTENT(IN) :: NUM
              CHARACTER(LEN=50) :: GET_FILE_NAME_0
            END FUNCTION GET_FILE_NAME
          END INTERFACE 
        END MODULE GET_FILE_NAME__genmod
