        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_TIMES_ETC__genmod
          INTERFACE 
            SUBROUTINE GET_TIMES_ETC(DATASET_NAME,TIMES,                &
     &FILE_NUM_FOR_TIME,TIME_NUM_FOR_TIME,NUM_TIMES,NUM_FILES,          &
     &JDATE_FOR_FILE,NX,NY,MAX_TIMES,MAX_FILES)
              INTEGER(KIND=4), INTENT(IN) :: MAX_FILES
              INTEGER(KIND=4), INTENT(IN) :: MAX_TIMES
              CHARACTER(LEN=50), INTENT(IN) :: DATASET_NAME
              REAL(KIND=8), INTENT(OUT) :: TIMES(MAX_TIMES)
              INTEGER(KIND=4), INTENT(OUT) :: FILE_NUM_FOR_TIME(        &
     &MAX_TIMES)
              INTEGER(KIND=4), INTENT(OUT) :: TIME_NUM_FOR_TIME(        &
     &MAX_TIMES)
              INTEGER(KIND=4), INTENT(OUT) :: NUM_TIMES
              INTEGER(KIND=4), INTENT(OUT) :: NUM_FILES
              INTEGER(KIND=4), INTENT(OUT) :: JDATE_FOR_FILE(MAX_FILES)
              INTEGER(KIND=4), INTENT(OUT) :: NX
              INTEGER(KIND=4), INTENT(OUT) :: NY
            END SUBROUTINE GET_TIMES_ETC
          END INTERFACE 
        END MODULE GET_TIMES_ETC__genmod
