        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_BRACKET__genmod
          INTERFACE 
            SUBROUTINE GET_BRACKET(TIME,INPUT_TIMES,TIME_NUM_1,         &
     &GOT_BRACKET,NUM_TIMES)
              INTEGER(KIND=4), INTENT(IN) :: NUM_TIMES
              REAL(KIND=8), INTENT(IN) :: TIME
              REAL(KIND=8), INTENT(IN) :: INPUT_TIMES(NUM_TIMES)
              INTEGER(KIND=4), INTENT(OUT) :: TIME_NUM_1
              LOGICAL(KIND=4), INTENT(OUT) :: GOT_BRACKET
            END SUBROUTINE GET_BRACKET
          END INTERFACE 
        END MODULE GET_BRACKET__genmod
