        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE GET_SFLUX_INPUTS__genmod
          INTERFACE 
            SUBROUTINE GET_SFLUX_INPUTS
            END SUBROUTINE GET_SFLUX_INPUTS
          END INTERFACE 
        END MODULE GET_SFLUX_INPUTS__genmod
