        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE HALT_ERROR__genmod
          INTERFACE 
            SUBROUTINE HALT_ERROR(MESSAGE)
              CHARACTER(*), INTENT(IN) :: MESSAGE
            END SUBROUTINE HALT_ERROR
          END INTERFACE 
        END MODULE HALT_ERROR__genmod
