        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:11 2011
        MODULE HGRAD_NODES__genmod
          INTERFACE 
            SUBROUTINE HGRAD_NODES(IHBND,NVRT1,NPA1,NSA1,VAR_ND,DVAR_DXY&
     &)
              INTEGER(KIND=4), INTENT(IN) :: NSA1
              INTEGER(KIND=4), INTENT(IN) :: NPA1
              INTEGER(KIND=4), INTENT(IN) :: NVRT1
              INTEGER(KIND=4), INTENT(IN) :: IHBND
              REAL(KIND=8), INTENT(IN) :: VAR_ND(NVRT1,NPA1)
              REAL(KIND=8), INTENT(OUT) :: DVAR_DXY(2,NVRT1,NSA1)
            END SUBROUTINE HGRAD_NODES
          END INTERFACE 
        END MODULE HGRAD_NODES__genmod
