        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:20 2011
        MODULE INIT_INTER_BTRACK__genmod
          INTERFACE 
            SUBROUTINE INIT_INTER_BTRACK
            END SUBROUTINE INIT_INTER_BTRACK
          END INTERFACE 
        END MODULE INIT_INTER_BTRACK__genmod
