        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE INTERP_TIME__genmod
          INTERFACE 
            SUBROUTINE INTERP_TIME(DATASET_NAME,TIME,DATA_NAME,TIME_1,  &
     &FILE_NUM_1,FILE_TIME_1,TIME_2,FILE_NUM_2,FILE_TIME_2,DATA_OUT,NX, &
     &NY)
              INTEGER(KIND=4), INTENT(IN) :: NY
              INTEGER(KIND=4), INTENT(IN) :: NX
              CHARACTER(*), INTENT(IN) :: DATASET_NAME
              REAL(KIND=8), INTENT(IN) :: TIME
              CHARACTER(*), INTENT(IN) :: DATA_NAME
              REAL(KIND=8), INTENT(IN) :: TIME_1
              INTEGER(KIND=4), INTENT(IN) :: FILE_NUM_1
              INTEGER(KIND=4), INTENT(IN) :: FILE_TIME_1
              REAL(KIND=8), INTENT(IN) :: TIME_2
              INTEGER(KIND=4), INTENT(IN) :: FILE_NUM_2
              INTEGER(KIND=4), INTENT(IN) :: FILE_TIME_2
              REAL(KIND=8), INTENT(OUT) :: DATA_OUT(NX,NY)
            END SUBROUTINE INTERP_TIME
          END INTERFACE 
        END MODULE INTERP_TIME__genmod
