        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:20 2011
        MODULE INTER_BTRACK__genmod
          INTERFACE 
            SUBROUTINE INTER_BTRACK(ITIME,NBT,BTLIST)
              USE ELFE_MSGP
              USE ELFE_GLBL
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              INTEGER(KIND=4), INTENT(IN) :: NBT
              TYPE (BT_TYPE), INTENT(INOUT) :: BTLIST(MXNBT)
            END SUBROUTINE INTER_BTRACK
          END INTERFACE 
        END MODULE INTER_BTRACK__genmod
