        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE INTERP_GRID__genmod
          INTERFACE 
            SUBROUTINE INTERP_GRID(DATA_OUT,DATA_IN,WEIGHT,             &
     &IN_ELEM_FOR_OUT_NODE,ELEM_NODES,NUM_ELEMS,NODE_I,NODE_J,NUM_NODES,&
     &NUM_NODES_OUT,NX,NY)
              INTEGER(KIND=4), INTENT(IN) :: NY
              INTEGER(KIND=4), INTENT(IN) :: NX
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES_OUT
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES
              INTEGER(KIND=4), INTENT(IN) :: NUM_ELEMS
              REAL(KIND=8), INTENT(OUT) :: DATA_OUT(NUM_NODES_OUT)
              REAL(KIND=8), INTENT(IN) :: DATA_IN(NX,NY)
              REAL(KIND=8), INTENT(IN) :: WEIGHT(NUM_NODES_OUT,3)
              INTEGER(KIND=4), INTENT(IN) :: IN_ELEM_FOR_OUT_NODE(      &
     &NUM_NODES_OUT)
              INTEGER(KIND=4), INTENT(IN) :: ELEM_NODES(NUM_ELEMS,3)
              INTEGER(KIND=4), INTENT(IN) :: NODE_I(NUM_NODES)
              INTEGER(KIND=4), INTENT(IN) :: NODE_J(NUM_NODES)
            END SUBROUTINE INTERP_GRID
          END INTERFACE 
        END MODULE INTERP_GRID__genmod
