        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:11 2011
        MODULE KRONECKER__genmod
          INTERFACE 
            FUNCTION KRONECKER(I,J) RESULT(KRONECKER_0)
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(IN) :: J
              INTEGER(KIND=4) :: KRONECKER_0
            END FUNCTION KRONECKER
          END INTERFACE 
        END MODULE KRONECKER__genmod
