        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:21 2011
        MODULE LINDEX__genmod
          INTERFACE 
            FUNCTION LINDEX(NODE,IE) RESULT(LINDEX_0)
              INTEGER(KIND=4), INTENT(IN) :: NODE
              INTEGER(KIND=4), INTENT(IN) :: IE
              INTEGER(KIND=4) :: LINDEX_0
            END FUNCTION LINDEX
          END INTERFACE 
        END MODULE LINDEX__genmod
