        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:11 2011
        MODULE NODALVEL__genmod
          INTERFACE 
            SUBROUTINE NODALVEL(IFLTYPE)
              USE ELFE_GLBL
              INTEGER(KIND=4), INTENT(IN) :: IFLTYPE(MAX(1,NOPE_GLOBAL))
            END SUBROUTINE NODALVEL
          END INTERFACE 
        END MODULE NODALVEL__genmod
