        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:22 2011
        MODULE PARTITION_HGRID__genmod
          INTERFACE 
            SUBROUTINE PARTITION_HGRID
            END SUBROUTINE PARTITION_HGRID
          END INTERFACE 
        END MODULE PARTITION_HGRID__genmod
