        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE READ_COORD__genmod
          INTERFACE 
            SUBROUTINE READ_COORD(FILE_NAME,DATA_NAME,COORD,NX,NY)
              INTEGER(KIND=4), INTENT(IN) :: NY
              INTEGER(KIND=4), INTENT(IN) :: NX
              CHARACTER(LEN=50), INTENT(IN) :: FILE_NAME
              CHARACTER(LEN=50), INTENT(IN) :: DATA_NAME
              REAL(KIND=8), INTENT(OUT) :: COORD(NX,NY)
            END SUBROUTINE READ_COORD
          END INTERFACE 
        END MODULE READ_COORD__genmod
