        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:19 2011
        MODULE REPORT_TIMERS__genmod
          INTERFACE 
            SUBROUTINE REPORT_TIMERS
            END SUBROUTINE REPORT_TIMERS
          END INTERFACE 
        END MODULE REPORT_TIMERS__genmod
