        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE ROTATE_WINDS__genmod
          INTERFACE 
            SUBROUTINE ROTATE_WINDS(U,V,NUM_NODES_OUT)
              INTEGER(KIND=4) :: NUM_NODES_OUT
              REAL(KIND=8) :: U(NUM_NODES_OUT)
              REAL(KIND=8) :: V(NUM_NODES_OUT)
            END SUBROUTINE ROTATE_WINDS
          END INTERFACE 
        END MODULE ROTATE_WINDS__genmod
