        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:21 2011
        MODULE SOLVE_JCG_QNON__genmod
          INTERFACE 
            SUBROUTINE SOLVE_JCG_QNON(ITIME,MOITN,MXITN,RTOL,NVRT1,MNEI1&
     &,NP1,NPA1,QMATR,QHAT,QIR)
              USE ELFE_GLBL
              INTEGER(KIND=4), INTENT(IN) :: NPA1
              INTEGER(KIND=4), INTENT(IN) :: NP1
              INTEGER(KIND=4), INTENT(IN) :: MNEI1
              INTEGER(KIND=4), INTENT(IN) :: NVRT1
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              INTEGER(KIND=4), INTENT(IN) :: MOITN
              INTEGER(KIND=4), INTENT(IN) :: MXITN
              REAL(KIND=8), INTENT(IN) :: RTOL
              REAL(KIND=8), INTENT(IN) :: QMATR(NVRT1,-1:1,0:(MNEI1+1), &
     &NP1)
              REAL(KIND=8), INTENT(OUT) :: QHAT(NVRT1,NPA1)
              REAL(KIND=8), INTENT(IN) :: QIR(NVRT1,NP1)
            END SUBROUTINE SOLVE_JCG_QNON
          END INTERFACE 
        END MODULE SOLVE_JCG_QNON__genmod
