        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:08 2011
        MODULE TURB_FLUXES__genmod
          INTERFACE 
            SUBROUTINE TURB_FLUXES(NUM_NODES,U_AIR,V_AIR,P_AIR,T_AIR,   &
     &Q_AIR,SEN_FLUX,LAT_FLUX,TAU_XZ,TAU_YZ)
              INTEGER(KIND=4), INTENT(IN) :: NUM_NODES
              REAL(KIND=8), INTENT(IN) :: U_AIR(NUM_NODES)
              REAL(KIND=8), INTENT(IN) :: V_AIR(NUM_NODES)
              REAL(KIND=8), INTENT(IN) :: P_AIR(NUM_NODES)
              REAL(KIND=8), INTENT(IN) :: T_AIR(NUM_NODES)
              REAL(KIND=8), INTENT(IN) :: Q_AIR(NUM_NODES)
              REAL(KIND=8), INTENT(OUT) :: SEN_FLUX(NUM_NODES)
              REAL(KIND=8), INTENT(OUT) :: LAT_FLUX(NUM_NODES)
              REAL(KIND=8), INTENT(OUT) :: TAU_XZ(NUM_NODES)
              REAL(KIND=8), INTENT(OUT) :: TAU_YZ(NUM_NODES)
            END SUBROUTINE TURB_FLUXES
          END INTERFACE 
        END MODULE TURB_FLUXES__genmod
