        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:19 2011
        MODULE WRITE_HEADER1__genmod
          INTERFACE 
            SUBROUTINE WRITE_HEADER1
            END SUBROUTINE WRITE_HEADER1
          END INTERFACE 
        END MODULE WRITE_HEADER1__genmod
