        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:19 2011
        MODULE WRITE_HEADER0__genmod
          INTERFACE 
            SUBROUTINE WRITE_HEADER0(ITHS,IT)
              INTEGER(KIND=4), INTENT(IN) :: ITHS
              INTEGER(KIND=4), INTENT(IN) :: IT
            END SUBROUTINE WRITE_HEADER0
          END INTERFACE 
        END MODULE WRITE_HEADER0__genmod
