        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 27 11:48:19 2011
        MODULE WRITE_OBE__genmod
          INTERFACE 
            SUBROUTINE WRITE_OBE
            END SUBROUTINE WRITE_OBE
          END INTERFACE 
        END MODULE WRITE_OBE__genmod
