        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 20 15:46:17 2011
        MODULE XERBLA__genmod
          INTERFACE 
            SUBROUTINE XERBLA(SRNAME,INFO)
              CHARACTER(LEN=6) :: SRNAME
              INTEGER(KIND=4) :: INFO
            END SUBROUTINE XERBLA
          END INTERFACE 
        END MODULE XERBLA__genmod
